export default [
  {
    icon: 'anchor-icon',
    title: 'Data Master',
    children: [
      {
        icon: 'hand-click-icon',
        title: 'All Product',
        route: 'all-product-read',
        resource: 'all-product-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Product Type',
        route: 'product-type-read',
        resource: 'product-type-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Product Category',
        route: 'product-category-read',
        resource: 'product-category-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Barcode Product',
        route: 'barcode-product-read',
        resource: 'barcode-product-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Product Brand',
        route: 'product-brand-read',
        resource: 'product-brand-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Unit Product',
        route: 'unit-product-read',
        resource: 'unit-product-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Variants Product',
        route: 'variants-product-read',
        resource: 'variants-product-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Discount Type',
        route: 'discount-type-read',
        resource: 'discount-type-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Region',
        route: 'region-read',
        resource: 'region-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'District',
        route: 'district-read',
        resource: 'district-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Salesman',
        resource: 'salesman-read',
        route: 'salesman-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Warehouse List',
        route: 'warehouse-list-read',
        resource: 'warehouse-list-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Customers List',
        resource: 'customers-list-read',
        route: 'customers-list-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Customers Type',
        route: 'customers-type-read',
        resource: 'customers-type-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Supplier List',
        route: 'supplier-list-read',
        resource: 'supplier-list-read',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Banks List',
        route: 'banks-list-read',
        resource: 'banks-list-read',
        action: 'read',
      },
    ]
  },
]
  